import { Society, ServiceCategory, ServiceItem, Booking, ServiceCamp, NotificationItem, Review } from './types';

export const INITIAL_SOCIETIES: Society[] = [
  {
    id: 'basileo',
    name: 'Basileo Society',
    location: 'Pimple Gurav',
    city: 'Pune',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBB7vOQ5vzP1KvyvwoCMsFC_rTSCY4dR12hsRAj7yMm8f04z2Y1iB5OW6EY9QEFW3YYInVqiwi1jQFP9CGg0yPsFBgaGQE9gDdbKBm79fMxN7XgRLsswoF5YJ0mAeataES_K44oRrbCrBVNfMmbfE-4HcCIXg48ypQtPfcy9U0I1nre2UHdE5qpKiZnssIN5OHQ5tgbqnn_tTp7pvRzwPx7eVH1QWTB-A7V6SMsxXBBQW5xqT4AiL8O',
    flatsCount: 380,
  },
  {
    id: 'green-valley',
    name: 'Green Valley Society',
    location: 'Kothrud',
    city: 'Pune',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAG6yB0qNgkhrgUO6e6tvj4OYNHqv4abM0_aZlEEADHtoNz9oBHqOEp7JfWUHbSnmnLJmSPqkYs61XWQosGugRFc-i8GsCXKIppvP0SlnRhv5T1Qwu3LarV9UUG1MvSH_xC-tBeuqMcvS-ujSqIicBHequmJ0v3htKVpi-jd5xnMvwB2tHHayZyOTa8RV18l-Guuq5niTjnUyRLAaJthoSK-7j4M2GXJ3rcVF4QXnMhgXsoXspWOAMD',
    flatsCount: 420,
  },
  {
    id: 'amanora',
    name: 'Amanora Park Town',
    location: 'Hadapsar',
    city: 'Pune',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBB7vOQ5vzP1KvyvwoCMsFC_rTSCY4dR12hsRAj7yMm8f04z2Y1iB5OW6EY9QEFW3YYInVqiwi1jQFP9CGg0yPsFBgaGQE9gDdbKBm79fMxN7XgRLsswoF5YJ0mAeataES_K44oRrbCrBVNfMmbfE-4HcCIXg48ypQtPfcy9U0I1nre2UHdE5qpKiZnssIN5OHQ5tgbqnn_tTp7pvRzwPx7eVH1QWTB-A7V6SMsxXBBQW5xqT4AiL8O',
    flatsCount: 850,
  }
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'electrical',
    name: 'Electrical',
    iconName: 'electrical_services',
    colorClass: 'text-on-primary-fixed',
    bgColorClass: 'bg-primary-fixed',
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    iconName: 'plumbing',
    colorClass: 'text-on-secondary-container',
    bgColorClass: 'bg-secondary-container',
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    iconName: 'cleaning_services',
    colorClass: 'text-on-tertiary-fixed',
    bgColorClass: 'bg-tertiary-fixed',
  },
  {
    id: 'ac-appliance',
    name: 'AC & Appliance',
    iconName: 'ac_unit',
    colorClass: 'text-on-primary-fixed',
    bgColorClass: 'bg-primary-fixed-dim',
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    iconName: 'handyman',
    colorClass: 'text-on-tertiary-fixed',
    bgColorClass: 'bg-tertiary-fixed-dim',
  },
  {
    id: 'painting',
    name: 'Painting',
    iconName: 'format_paint',
    colorClass: 'text-on-secondary-fixed',
    bgColorClass: 'bg-secondary-fixed',
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    iconName: 'pest_control',
    colorClass: 'text-on-error-container',
    bgColorClass: 'bg-error-container',
  },
  {
    id: 'home-maintenance',
    name: 'Home Mainten.',
    iconName: 'home_repair_service',
    colorClass: 'text-on-surface-variant',
    bgColorClass: 'bg-surface-variant',
  },
];

export const POPULAR_SERVICES: ServiceItem[] = [
  {
    id: 'srv-switch-repair',
    title: 'Switch Repair',
    category: 'Electrical',
    duration: 'Usually takes 1 hr',
    price: 250,
    originalPrice: 350,
    rating: 4.9,
    reviewCount: '1.2k',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvfkeHVzhmGiDa6KC89lZqQE3v0ggzzPjqM5Y0KmxLhzborVt8A2yszUIjZ0tVqUqC-NaKXM9SpSYPa8CI35mYScm9a0P4CdFB7oqOZ-ooc8ftKO5d3syyQuhEGAA1FLmVQ1_S8hh-OpD9zlglrJcqIKvm094uVt7Hhtw4UFBpW0JBTasO0UgSisZ0k2guPMUlPrHzMYYeVwgoUBjd9dQysOi34_L7x7AAQrLbuh1tUNTC_nF-6XNa',
    description: 'Expert diagnostic and repair of malfunctioning modular switches, MCBs, or loose wire sockets.',
    popular: true,
  },
  {
    id: 'srv-tap-leakage',
    title: 'Tap Leakage',
    category: 'Plumbing',
    duration: 'Usually takes 30 min',
    price: 150,
    originalPrice: 220,
    rating: 4.8,
    reviewCount: '940',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaqx7adQJW15HLNVeVAYr8jLkHT600wfFWctEI894vkunpz3vZNDNYkxmlzMlX9zCxjsKgkoPZ-X3GuIF4htvBkfDCgdGs4uyGqslSXAB4ZubExsQGtHhQ-Kga3L-UukJ-DXsbz2qRqZ-jleks4vkFxJMp9vEXrlfE0ngX48R_NMQLmxJELu_FG19mxHKB04BEahYcJ5fYp9GQk2OX1nPo-D3FqI5k0kKG1UZBhirzo81PsA9GJcR0',
    description: 'Quick resolution of dripping taps, kitchen sink washer replacements, and seal inspection.',
    popular: true,
  },
  {
    id: 'srv-deep-cleaning',
    title: 'Deep Cleaning',
    category: 'Cleaning',
    duration: 'Usually takes 4-6 hrs',
    price: 1999,
    originalPrice: 2800,
    rating: 4.9,
    reviewCount: '3.4k',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgKB7dCf76lxHAvmHudZI94k69P9moDT-oCl1hUomfhJZ1DHGGi3p62-E42J8xCRoveKi49YYd07JNZIg34RVC008a1QsFDJO3RpwNzruSCsvaQrHIRUjrOJnFji78lKY6TusW_JqCIARCNj1rFYnzGQbyRkcTkx8AAC79W3lBcmO8LeJWxTw4vemMa1Tgpy_9OyIiFBW5E3JBf4GNu7ENpQfQXlueO3gijeuuMthp-t9WduJgv9uG',
    description: 'Intense scrubbing, vacuuming, window track cleaning, and chemical sanitization of entire home.',
    popular: true,
  },
  {
    id: 'srv-full-home-cleaning',
    title: 'Full Home Cleaning',
    category: 'Cleaning',
    duration: 'Usually takes 5-7 hrs',
    price: 2499,
    originalPrice: 3199,
    rating: 4.8,
    reviewCount: '12k+',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCG68qxi7CnrTjS5JMgVrPfa7OINQp23KbayDww8OWUQdtWybbELNq8CS42-DN_1OErR6vtDoxu11qpyLl4Q1y33xCthHGS5D70uU0jLNFNMP22t9o78HxR8FRsb8EI2vMonRUbBoroKfbvUUP3pzgcfhxH_8dXfPcoyqcIkpk11zWRdRmAlKcM0NXjzaAg0cs3-q1H-m1_dKIuUdnwWUkcDft1dDLKsnSys6NMbRgg6_hHrNasqyvHiQTuDe4ejDROQgw',
    description: 'Society bestseller complete deep home overhaul including kitchen grease removal, bathroom tile de-scaling, and upholstery dusting.',
    popular: true,
  },
  {
    id: 'srv-ac-service',
    title: 'AC Service & Jet Clean',
    category: 'AC & Appliance',
    duration: 'Usually takes 45 min',
    price: 599,
    originalPrice: 850,
    rating: 4.9,
    reviewCount: '5.1k',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvfkeHVzhmGiDa6KC89lZqQE3v0ggzzPjqM5Y0KmxLhzborVt8A2yszUIjZ0tVqUqC-NaKXM9SpSYPa8CI35mYScm9a0P4CdFB7oqOZ-ooc8ftKO5d3syyQuhEGAA1FLmVQ1_S8hh-OpD9zlglrJcqIKvm094uVt7Hhtw4UFBpW0JBTasO0UgSisZ0k2guPMUlPrHzMYYeVwgoUBjd9dQysOi34_L7x7AAQrLbuh1tUNTC_nF-6XNa',
    description: 'High pressure foam wash, coil disinfection, gas pressure check, and drain line flushing.',
    popular: false,
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'BK-10492',
    serviceTitle: 'AC Service & Repair',
    category: 'Appliances',
    status: 'on_the_way',
    etaMinutes: 12,
    scheduledTime: 'Today, 11:30 AM',
    workerName: 'Rahul Patil',
    workerPhone: '+91 98231 44521',
    workerPhoto: 'https://lh3.googleusercontent.com/aida/AEtjO1VNbnYo9bWQsN6v-mc3hRP3S_rcFxKxU52Mw-3nVBtWXkp7E6lkXQiU24na4MzRxKs48sbxVdt1nAUAKC9ZmEJl1oO7XdRfIstnTpvEYjzRiFxb08YyD8bPPHfymQZSsz9TOyj0RzabFX8x7VjVnVR2V1tb6eok-94C2CrQ16p9beF_zQ-1MINrwBFFL_M4Ndw2gE09C2vaipzjJAiBUkevJDzCT0kdQs_yw0YHTFKLC0k4_E8YQpaNT-I',
    workerRating: 4.9,
    otp: '5842',
    price: 1200,
    address: 'Flat B-402, Basileo Society, Pimple Gurav, Pune',
    notes: 'Indoor split AC making light rattling noise and cooling slowly.',
  },
  {
    id: 'BK-10493',
    serviceTitle: 'Electrician - Switch Repair',
    category: 'Electrical',
    status: 'assigned',
    scheduledTime: 'Tomorrow, 10:00 AM',
    workerName: 'Amit Shinde',
    workerPhone: '+91 94220 89112',
    workerPhoto: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD__6ho0Z9H9zljUy4Iq0MYGN0Ol_yf0ZppCNwlJ-vWAT5hNhzZFv_DreYgzxG1ojoeHeWYxatE8RJsDQ3IZHqbw6mJGI2QUqquhVNrgotOas9WyJCtodTadU71toN5ZqWJBrAea2XSc24Lv2oT4M4GEo2WBUHe_qieIAp93otLeF2366Rm7aqt46DsLmuMiA6_iSuRxBb3h7eVgvSqJC-_iXlAgiWN_0Q6taI2W2DRX3PLD1c_fKK2',
    workerRating: 4.8,
    otp: '3190',
    price: 250,
    address: 'Flat B-402, Basileo Society, Pimple Gurav, Pune',
    notes: 'Master bedroom main switchboard spark issue.',
  }
];

export const SERVICE_CAMPS: ServiceCamp[] = [
  {
    id: 'camp-ac',
    category: 'Appliances',
    title: 'AC Service Camp',
    dateStr: 'Saturday, 10 AM',
    priceInfo: '₹1,200/unit (Group price)',
    joinedCount: 18,
    targetCount: 25,
    badgeClass: 'bg-secondary-container text-on-secondary-container',
    borderAccentColor: 'bg-primary',
  },
  {
    id: 'camp-cleaning',
    category: 'Maintenance',
    title: 'Deep Cleaning Week',
    dateStr: 'Starts Monday',
    priceInfo: 'Multiple packages available',
    joinedCount: 8,
    targetCount: 15,
    badgeClass: 'bg-secondary-container text-on-secondary-container',
    borderAccentColor: 'bg-secondary',
    hasPackages: true,
  },
  {
    id: 'camp-plumbing',
    category: 'Plumbing',
    title: 'Monsoon Pipe & Drain Inspection',
    dateStr: 'Wednesday, 4 PM',
    priceInfo: 'Free Society Checkup',
    joinedCount: 24,
    targetCount: 30,
    badgeClass: 'bg-primary-fixed text-on-primary-fixed',
    borderAccentColor: 'bg-primary',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'service',
    title: 'Service Update',
    timeAgo: '2m ago',
    description: 'Rahul Patil is on the way for your AC service.',
    isRead: false,
    section: 'today',
    targetTab: 'bookings',
  },
  {
    id: 'notif-2',
    type: 'community',
    title: 'New Community Request',
    timeAgo: '1h ago',
    description: '5 neighbors in Green Valley Society joined the AC Camp.',
    isRead: false,
    section: 'today',
    targetTab: 'community',
  },
  {
    id: 'notif-3',
    type: 'service',
    title: 'AC Service Confirmed',
    timeAgo: '3h ago',
    description: 'Your service is scheduled for tomorrow at 10:00 AM.',
    isRead: true,
    section: 'today',
    targetTab: 'bookings',
  },
  {
    id: 'notif-4',
    type: 'urgent',
    title: 'Emergency Support',
    timeAgo: 'Yesterday',
    description: 'Your dispute for the last Plumbing service is being reviewed.',
    isRead: true,
    section: 'yesterday',
    targetTab: 'profile',
  },
  {
    id: 'notif-5',
    type: 'payment',
    title: 'Payment Successful',
    timeAgo: 'Yesterday',
    description: 'Receipt for Electrician service is available.',
    isRead: true,
    section: 'yesterday',
    targetTab: 'bookings',
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Sneha M.',
    tower: 'Tower A-204',
    rating: 5,
    comment: 'The NetNivas service was amazing! The professional arrived on time and did a thorough job. Highly recommend it to fellow Basileo residents!',
    avatarInitial: 'S',
  },
  {
    id: 'rev-2',
    author: 'Amit K.',
    tower: 'Tower B-1102',
    rating: 5,
    comment: 'Participating in the society group camps has saved us over ₹3,500 this season. Great cooperative gig worker initiative!',
    avatarInitial: 'A',
  }
];
